# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

WORKLOAD_NAME: "GameAnalyticsPipeline"
CDK_VERSION: "2.92.0"
NODE_VERSION: "latest"
PYTHON_VERSION: "3.8"
DEV_MODE: true
ENABLE_STREAMING_ANALYTICS: true
STREAM_SHARD_COUNT: 1
RAW_EVENTS_PREFIX: "raw_events"
PROCESSED_EVENTS_PREFIX: "processed_events"
RAW_EVENTS_TABLE: "raw_events"
GLUE_TMP_PREFIX: "glueetl-tmp"
S3_BACKUP_MODE: false
CLOUDWATCH_RETENTION_DAYS: 30
API_STAGE_NAME: "live"
EMAIL_ADDRESS: "munjinya@amazon.co.jp"
GITHUB_USERNAME: "munjinya-aws"
GITHUB_REPO_NAME: "guidance-for-game-analytics-pipeline-on-aws"
CONNECTION_ARN: "arn:aws:codeconnections:ap-northeast-1:021891573108:connection/7caa284f-18f5-407e-aab3-385048145172"
accounts:
  - NAME: "dev"
    ACCOUNT: "021891573108"
    REGION: "ap-northeast-1"
  - NAME: "dummy"
    ACCOUNT: "021891573108"
    REGION: "ap-northeast-1"

# CONNECTION_ARN: "arn:aws:codeconnections:ap-northeast-1:012476690837:connection/1ecd1351-75a5-4901-9afd-aee02df0b93d"
# accounts:
#   - NAME: "dev"
#     ACCOUNT: "012476690837"
#     REGION: "ap-northeast-1"
#   - NAME: "dummy"
#     ACCOUNT: "012476690837"
#     REGION: "ap-northeast-1"

